### ISSUE TITLE
Homework Feedback JS2 Week 3

### ISSUE THREAD

**Issue by r0hitsharma** [DEJENERUTA/hyf-homework#1]
Please add more of the homework so I can take a look at it as well.

https://github.com/DEJENERUTA/hyf-homework/blob/a229971288ea64c34853cffd5484c61953b71d60/javascript/javascript2/week3/functionsAsAVariable.js#L3

Prefer to use `console.log` instead of `alert` now :)

**Comment by DEJENERUTA** [comment]
Thanks a lot
